version: '3.8'

services:
  app:
    image: flask-task-manager
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: